//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaLuanSteam.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_THIETBISTEAMEntities1 : DbContext
    {
        public QL_THIETBISTEAMEntities1()
            : base("name=QL_THIETBISTEAMEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CT_DonDatHangNCC> CT_DonDatHangNCC { get; set; }
        public DbSet<CT_PHIEUDATHANG> CT_PHIEUDATHANG { get; set; }
        public DbSet<CT_PHIEUNHAPHANG> CT_PHIEUNHAPHANG { get; set; }
        public DbSet<DonDatHangNCC> DonDatHangNCCs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<LIENHE> LIENHEs { get; set; }
        public DbSet<LOAISANPHAM> LOAISANPHAMs { get; set; }
        public DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public DbSet<NHANVIEN> NHANVIENs { get; set; }
        public DbSet<PHANQUYEN> PHANQUYENs { get; set; }
        public DbSet<PHIEUDATHANG> PHIEUDATHANGs { get; set; }
        public DbSet<PHIEUGIAOHANG> PHIEUGIAOHANGs { get; set; }
        public DbSet<PHIEUNHAPHANG> PHIEUNHAPHANGs { get; set; }
        public DbSet<SALE> SALEs { get; set; }
        public DbSet<TINHTRANGDH> TINHTRANGDHs { get; set; }
        public DbSet<SPSALE> SPSALEs { get; set; }
        public DbSet<THONGTINSANPHAM> THONGTINSANPHAMs { get; set; }
    }
}
